### ISSUE TITLE
SoundCollect picture uploads

### ISSUE THREAD

**Issue by OtariOboladzeSfC** [ScienceForChange/SoundCollect_backend#23]
what are the guidelines for a picture upload? what are the restrictions? 
do we hide only faces? nude content? violence? @JohanaSfC 

@CarlosMillanSfC can you investigate what are available products/API calls?
https://www.edenai.co/post/top-10-explicit-content-detection-apis

**Comment by CarlosMillanSfC** [comment]
what is exactly the goal of the picture moderation? As @OtariOboladzeSfC asked: do we hide only faces? nude content? violence? @JohanaSfC 
Because if there is only "explicit" content the https://api4.ai/apis/nsfw seems kinda nice, my favorite so far, but i think it only moderates explicit content and not blur faces
